services:
  db: 
    image: postgres
    container_name: db_posgre
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    restart: always

  backend:
    container_name: flask_api
    ports:
      - "$SERVER_PORT:$SERVER_PORT"

    command: tail -f /dev/null
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/project
      - /project/__pypackages__/

    depends_on:
      - db